<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AdminMenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Clear existing menu items
        DB::table('admin_menu')->truncate();

        $menuItems = [
            // Dashboard (Root level)
            [
                'id' => 1,
                'parent_id' => 0,
                'order' => 1,
                'title' => 'Dashboard',
                'icon' => 'fa-tachometer-alt',
                'uri' => '/',
                'permission' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Patient Management
            [
                'id' => 2,
                'parent_id' => 0,
                'order' => 2,
                'title' => 'Patient Management',
                'icon' => 'fa-user-injured',
                'uri' => '',
                'permission' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'parent_id' => 2,
                'order' => 3,
                'title' => 'Patients',
                'icon' => 'fa-users',
                'uri' => 'patients',
                'permission' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'parent_id' => 2,
                'order' => 4,
                'title' => 'Patient Records',
                'icon' => 'fa-file-medical',
                'uri' => 'patient-records',
                'permission' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'parent_id' => 2,
                'order' => 5,
                'title' => 'Appointments',
                'icon' => 'fa-calendar-check',
                'uri' => 'appointments',
                'permission' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Medical Services
            [
                'id' => 6,
                'parent_id' => 0,
                'order' => 6,
                'title' => 'Medical Services',
                'icon' => 'fa-stethoscope',
                'uri' => '',
                'permission' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'parent_id' => 6,
                'order' => 7,
                'title' => 'Consultations',
                'icon' => 'fa-user-md',
                'uri' => 'consultations',
                'permission' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'parent_id' => 6,
                'order' => 8,
                'title' => 'Medical Services',
                'icon' => 'fa-procedures',
                'uri' => 'medical-services',
                'permission' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'parent_id' => 6,
                'order' => 9,
                'title' => 'Treatment Records',
                'icon' => 'fa-notes-medical',
                'uri' => 'treatment-records',
                'permission' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'parent_id' => 6,
                'order' => 10,
                'title' => 'Doctor Schedules',
                'icon' => 'fa-clock',
                'uri' => 'doctor-schedules',
                'permission' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Pharmacy & Inventory
            [
                'id' => 11,
                'parent_id' => 0,
                'order' => 11,
                'title' => 'Pharmacy & Inventory',
                'icon' => 'fa-pills',
                'uri' => '',
                'permission' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'parent_id' => 11,
                'order' => 12,
                'title' => 'Stock Items',
                'icon' => 'fa-boxes',
                'uri' => 'stock-items',
                'permission' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'parent_id' => 11,
                'order' => 13,
                'title' => 'Stock Categories',
                'icon' => 'fa-tags',
                'uri' => 'stock-item-categories',
                'permission' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'parent_id' => 11,
                'order' => 14,
                'title' => 'Dose Items',
                'icon' => 'fa-prescription-bottle',
                'uri' => 'dose-items',
                'permission' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'parent_id' => 11,
                'order' => 15,
                'title' => 'Stock Out Records',
                'icon' => 'fa-truck-loading',
                'uri' => 'stock-out-records',
                'permission' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Billing & Finance
            [
                'id' => 16,
                'parent_id' => 0,
                'order' => 16,
                'title' => 'Billing & Finance',
                'icon' => 'fa-dollar-sign',
                'uri' => '',
                'permission' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'parent_id' => 16,
                'order' => 17,
                'title' => 'Billing Items',
                'icon' => 'fa-receipt',
                'uri' => 'billing-items',
                'permission' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'parent_id' => 16,
                'order' => 18,
                'title' => 'Payment Records',
                'icon' => 'fa-credit-card',
                'uri' => 'payment-records',
                'permission' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'parent_id' => 16,
                'order' => 19,
                'title' => 'Financial Years',
                'icon' => 'fa-calendar-alt',
                'uri' => 'financial-years',
                'permission' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Enterprise Management
            [
                'id' => 20,
                'parent_id' => 0,
                'order' => 20,
                'title' => 'Enterprise Management',
                'icon' => 'fa-building',
                'uri' => '',
                'permission' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 21,
                'parent_id' => 20,
                'order' => 21,
                'title' => 'Enterprises',
                'icon' => 'fa-hospital',
                'uri' => 'enterprises',
                'permission' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 22,
                'parent_id' => 20,
                'order' => 22,
                'title' => 'Departments',
                'icon' => 'fa-sitemap',
                'uri' => 'departments',
                'permission' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 23,
                'parent_id' => 20,
                'order' => 23,
                'title' => 'Rooms',
                'icon' => 'fa-bed',
                'uri' => 'rooms',
                'permission' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // User Management
            [
                'id' => 24,
                'parent_id' => 0,
                'order' => 24,
                'title' => 'User Management',
                'icon' => 'fa-users-cog',
                'uri' => '',
                'permission' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 25,
                'parent_id' => 24,
                'order' => 25,
                'title' => 'Users',
                'icon' => 'fa-user',
                'uri' => 'users',
                'permission' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 26,
                'parent_id' => 24,
                'order' => 26,
                'title' => 'Roles',
                'icon' => 'fa-user-shield',
                'uri' => 'auth/roles',
                'permission' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 27,
                'parent_id' => 24,
                'order' => 27,
                'title' => 'Permissions',
                'icon' => 'fa-key',
                'uri' => 'auth/permissions',
                'permission' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Reports
            [
                'id' => 28,
                'parent_id' => 0,
                'order' => 28,
                'title' => 'Reports',
                'icon' => 'fa-chart-bar',
                'uri' => '',
                'permission' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 29,
                'parent_id' => 28,
                'order' => 29,
                'title' => 'Report Models',
                'icon' => 'fa-file-alt',
                'uri' => 'report-models',
                'permission' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // System Settings
            [
                'id' => 30,
                'parent_id' => 0,
                'order' => 30,
                'title' => 'System Settings',
                'icon' => 'fa-cogs',
                'uri' => '',
                'permission' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 31,
                'parent_id' => 30,
                'order' => 31,
                'title' => 'Menu',
                'icon' => 'fa-bars',
                'uri' => 'auth/menu',
                'permission' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 32,
                'parent_id' => 30,
                'order' => 32,
                'title' => 'System Logs',
                'icon' => 'fa-history',
                'uri' => 'auth/logs',
                'permission' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($menuItems as $item) {
            DB::table('admin_menu')->insert($item);
        }
    }
}
