-- SQL to create admin_users table with all required columns
-- Copy and paste this into phpMyAdmin if the table doesn't exist

DROP TABLE IF EXISTS `admin_users`;

CREATE TABLE `admin_users` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `enterprise_id` bigint(20) unsigned NULL,
    `name` varchar(255) NOT NULL,
    `email` varchar(255) NULL,
    `email_verified_at` timestamp NULL,
    `password` varchar(255) NOT NULL,
    `first_name` varchar(255) NULL,
    `last_name` varchar(255) NULL,
    `username` varchar(255) NULL,
    `phone_number_1` varchar(255) NULL,
    `phone_number_2` varchar(255) NULL,
    `date_of_birth` date NULL,
    `place_of_birth` varchar(255) NULL,
    `sex` enum('male','female','other') NULL,
    `home_address` text NULL,
    `current_address` text NULL,
    `nationality` varchar(255) NULL,
    `religion` varchar(255) NULL,
    `spouse_name` varchar(255) NULL,
    `spouse_phone` varchar(255) NULL,
    `father_name` varchar(255) NULL,
    `father_phone` varchar(255) NULL,
    `mother_name` varchar(255) NULL,
    `mother_phone` varchar(255) NULL,
    `languages` varchar(255) NULL,
    `emergency_person_name` varchar(255) NULL,
    `emergency_person_phone` varchar(255) NULL,
    `emergency_contact_relationship` varchar(255) NULL,
    `national_id_number` varchar(255) NULL,
    `passport_number` varchar(255) NULL,
    `tin` varchar(255) NULL,
    `nssf_number` varchar(255) NULL,
    `bank_name` varchar(255) NULL,
    `bank_account_number` varchar(255) NULL,
    `marital_status` varchar(255) NULL,
    `title` varchar(255) NULL,
    `company_id` bigint(20) unsigned NULL,
    `user_type` varchar(255) DEFAULT 'patient',
    `patient_status` varchar(255) NULL,
    `avatar` varchar(255) NULL,
    `intro` text NULL,
    `rate` decimal(8,2) DEFAULT 0,
    `belongs_to_company` varchar(255) NULL,
    `card_status` varchar(255) DEFAULT 'inactive',
    `card_number` varchar(255) NULL,
    `card_balance` decimal(15,2) DEFAULT 0,
    `card_accepts_credit` tinyint(1) DEFAULT 0,
    `card_max_credit` decimal(15,2) DEFAULT 0,
    `card_accepts_cash` tinyint(1) DEFAULT 1,
    `is_dependent` tinyint(1) DEFAULT 0,
    `dependent_status` varchar(255) NULL,
    `dependent_id` bigint(20) unsigned NULL,
    `card_expiry` date NULL,
    `belongs_to_company_status` varchar(255) NULL,
    `medical_history` text NULL,
    `allergies` text NULL,
    `current_medications` text NULL,
    `blood_type` varchar(255) NULL,
    `height` decimal(5,2) NULL,
    `weight` decimal(5,2) NULL,
    `insurance_provider` varchar(255) NULL,
    `insurance_policy_number` varchar(255) NULL,
    `insurance_expiry_date` date NULL,
    `family_doctor_name` varchar(255) NULL,
    `family_doctor_phone` varchar(255) NULL,
    `employment_status` varchar(255) NULL,
    `employer_name` varchar(255) NULL,
    `annual_income` decimal(15,2) NULL,
    `education_level` varchar(255) NULL,
    `preferred_language` varchar(255) NULL,
    `remember_token` varchar(100) NULL,
    `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `email` (`email`),
    UNIQUE KEY `username` (`username`),
    KEY `idx_enterprise_id` (`enterprise_id`),
    KEY `idx_user_type` (`user_type`),
    KEY `idx_card_number` (`card_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
